#!/bin/bash
#
# test configuration for radius_test script
# test should be ok with all decoded packets
#

# -H - radius server (example: radius.world.com)
# -P - destination port
# -S - password for communication between client (authenticatior) and radius
# -u - account (example: doe@world.com)
# -p - password 
# -m - authentication method
# -e - EAP protocol
# -M - MAC address in xx:xx:xx:xx:xx:xx format
cd ..
./rad_eap_test -H paralen -P 1812 -S trouba61 -u account -p pass_iiii -m WPA-EAP -e PEAP -c -M aa:bb:12:34:56:90 -i"Nazdar bazar" -d/tmp/tmp

