#!/bin/bash
#
# test configuration for radius_test script
# test tries to connect to non exist radius ( or downed radius ) with non default long timeout
#

# -H - radius server (example: radius.world.com)
# -P - destination port
# -S - password for communication between client (authenticatior) and radius
# -u - account (example: doe@world.com)
# -p - password 
# -m - authentication method
# -e - EAP protocol
# -t - timeout in seconds

cd ..
./rad_eap_test -H bad_radius -P 1812 -S trouba61 -u account -p iiiiii -m WPA-EAP -e PEAP -t 10

