#!/bin/bash
#
# test configuration for radius_test script
# test should be succesfull without verbose mode
#

# -H - radius server (example: radius.world.com)
# -P - destination port
# -S - password for communication between client (authenticatior) and radius
# -u - account (example: doe@world.com)
# -p - password 
# -m - authentication method
# -e - EAP protocol

cd ..
./rad_eap_test -H radius -P 1812 -S trouba61 -u test@ics.muni.cz -k /mnt/klic2/certifikat/testovaci_muni_tls/test_tls.key -j /mnt/klic2/certifikat/testovaci_muni_tls/test_tls.crt -a /home/polish/cesnet-ca.cz.pem.crt -m IEEE8021X -e TLS -t 15 -c 

